### PR TITLE
Handle unknown DB GlucoseValue SourceSensors

### LINKED ISSUE #3466: Regression with BG type ??
I have problems with updating from a 2 weeks old dev to the last dev version. Seems like something went bad in a commit....

Build is ok, update is ok. AAPS craches systematically when starting. Clearing cache doesn't help

This is the logcat when the upgraded AAPS tries to start.

### PR DESCRIPTION
**Pull request by plummer86**
Fixes #3466

Updated toSourceSensor to return 'UNKNOWN' SourceSensor for GlucoseValues that have undefined sensor enum values. This change prevents toSourceSensor from raising an exception when the source sensor enum is not found.

### CODE REVIEW

File: database/impl/src/main/kotlin/app/aaps/database/Converters.kt [hunk 1]
```diff
@@ -60,7 +60,12 @@ class Converters {
     fun fromSourceSensor(sourceSensor: GlucoseValue.SourceSensor?) = sourceSensor?.name
 
     @TypeConverter
-    fun toSourceSensor(sourceSensor: String?) = sourceSensor?.let { GlucoseValue.SourceSensor.valueOf(it) }
+    fun toSourceSensor(sourceSensor: String?): GlucoseValue.SourceSensor? {
+        return sourceSensor?.let {
+            GlucoseValue.SourceSensor.entries.find {
```
Comment (MilosKozak) [inline database/impl/src/main/kotlin/app/aaps/database/Converters.kt:65]: firstOrNull is the corect kotlin way
