### PR TITLE
Fix Autotune Fragment Crash (#1764)

### LINKED ISSUE #1764: [dev-k] Autotune throws FATAL EXCEPTION
@Philoul Is this interesting or helpful?
```
2022-05-23 09:48:31.304 2930-2930/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: info.nightscout.androidaps, PID: 2930
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Context.isUiContext()' on a null object reference
        at android.view.ViewConfiguration.get(ViewConfiguration.java:502)
        at android.view.View.<init>(View.java:5335)
        at android.view.View.<init>(View.java:5485)
        at android.view.ViewGroup.<init>(ViewGroup.java:699)
        at android.widget.LinearLayout.<init>(LinearLayout.java:254)
        at android.widget.LinearLayout.<init>(LinearLayout.java:250)
        at android.widget.LinearLayout.<init>(LinearLayout.java:246)
        at android.widget.LinearLayout.<init>(LinearLayout.java:242)
        at android.widget.TableLayout.<init>(TableLayout.java:91)
        at info.nightscout.androidaps.plugins.general.autotune.AutotuneFragment.showResults$lambda-41$lambda-40(AutotuneFragment.kt:391)
        at info.nightscout.androidaps.plugins.general.autotune.AutotuneFragment.$r8$lambda$ESyvUDAdq5HElXihWjE_BWA88Bs(Unknown Source:0)
        at info.nightscout.androidaps.plugins.general.autotune.AutotuneFragment$$ExternalSyntheticLambda2.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7700)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
```

### PR DESCRIPTION
**Pull request by Philoul**
I already included `_binding ?: return` in the beginning of `updateGui()`but it was probably not enough...
I added a new one at the beginning of `showResults()` and check context before `runOnUiThread`
Fix #1764

### CODE REVIEW

File: app/src/main/java/info/nightscout/androidaps/plugins/general/autotune/AutotuneFragment.kt [hunk 1]
```diff
@@ -381,55 +381,79 @@ class AutotuneFragment : DaggerFragment() {
     }
 
     private fun showResults() {
+        _binding ?: return
         Thread {
```
Comment (MilosKozak) [inline app/src/main/java/info/nightscout/androidaps/plugins/general/autotune/AutotuneFragment.kt:385]: btw is thread in thread necessary?

Comment (MilosKozak) [reply app/src/main/java/info/nightscout/androidaps/plugins/general/autotune/AutotuneFragment.kt:385]: and i'd move _binding check into most inner tread
